// Code generated by protoc-gen-go-harpy. DO NOT EDIT.
// versions:
// 	protoc-gen-go-harpy v0.0.0+ffce236
// 	protoc              v3.17.3
// source: github.com/dogmatiq/harpy/internal/testservice/service.proto

package testservice

import (
	"context"
	"errors"
	harpy "github.com/dogmatiq/harpy/runtime"
	proto "google.golang.org/protobuf/proto"
)

// TestService is an interface for the harpy.test.TestService service.
//
// It is used for both clients and servers.
type TestService interface {
	Unary(context.Context, *Request) (*Response, error)
	ServerStream(context.Context, *Request, chan<- *Response) error
	ClientStream(context.Context, <-chan *Request) (*Response, error)
	BidirectionalStream(context.Context, <-chan *Request, chan<- *Response) error
}

// harpy_TestService_Service is an implementation of the harpy.Service
// interface for the TestService service.
type harpy_TestService_Service struct {
	service TestService
}

// RegisterHarpyTestServiceServer registers a TestService service with a Harpy server.
func RegisterHarpyTestServiceServer(server harpy.Server, service TestService) {
	server.RegisterService(&harpy_TestService_Service{service})
}

func (a *harpy_TestService_Service) Name() string {
	return "TestService"
}

func (a *harpy_TestService_Service) Package() string {
	return "harpy.test"
}

func (a *harpy_TestService_Service) LookupMethod(name string) (harpy.Method, bool) {
	switch name {
	case "Unary":
		return &harpy_TestService_Unary_Method{a.service}, true
	case "ServerStream":
		return &harpy_TestService_ServerStream_Method{a.service}, true
	case "ClientStream":
		return &harpy_TestService_ClientStream_Method{a.service}, true
	case "BidirectionalStream":
		return &harpy_TestService_BidirectionalStream_Method{a.service}, true
	default:
		return nil, false
	}
}

// harpy_TestService_Unary_Method is an implementation of the harpy.Method
// interface for the TestService.Unary() method.
type harpy_TestService_Unary_Method struct {
	service TestService
}

func (m *harpy_TestService_Unary_Method) Name() string {
	return "Unary"
}

func (m *harpy_TestService_Unary_Method) ClientStreaming() bool {
	return false
}

func (m *harpy_TestService_Unary_Method) ServerStreaming() bool {
	return false
}

func (m *harpy_TestService_Unary_Method) NewCall(ctx context.Context) harpy.Call {
	return newHarpy_TestService_Unary_Call(ctx, m.service)
}

// harpy_TestService_Unary_Call is an implementation of the harpy.Call
// interface for the TestService.Unary() method.
type harpy_TestService_Unary_Call struct {
	ctx     context.Context
	service TestService
	done    chan struct{}
	res     *Response
	err     error
}

// newHarpy_TestService_Unary_Call returns a new harpy.Call for the TestService.Unary() method.
func newHarpy_TestService_Unary_Call(ctx context.Context, service TestService) harpy.Call {
	return &harpy_TestService_Unary_Call{ctx, service, make(chan struct{}), nil, nil}
}

func (c *harpy_TestService_Unary_Call) Recv() (proto.Message, bool, error) {
	select {
	case <-c.ctx.Done():
		return nil, false, c.ctx.Err()
	case <-c.done:
		return c.res, c.err == nil, c.err
	}
}

func (c *harpy_TestService_Unary_Call) Send(unmarshal harpy.RawMessage) error {
	req := &Request{}
	if err := unmarshal(req); err != nil {
		return err
	}

	c.res, c.err = c.service.Unary(c.ctx, req)
	close(c.done)

	return nil
}

func (c *harpy_TestService_Unary_Call) Done() {}

// harpy_TestService_ServerStream_Method is an implementation of the harpy.Method
// interface for the TestService.ServerStream() method.
type harpy_TestService_ServerStream_Method struct {
	service TestService
}

func (m *harpy_TestService_ServerStream_Method) Name() string {
	return "ServerStream"
}

func (m *harpy_TestService_ServerStream_Method) ClientStreaming() bool {
	return false
}

func (m *harpy_TestService_ServerStream_Method) ServerStreaming() bool {
	return true
}

func (m *harpy_TestService_ServerStream_Method) NewCall(ctx context.Context) harpy.Call {
	return newHarpy_TestService_ServerStream_Call(ctx, m.service)
}

// harpy_TestService_ServerStream_Call is an implementation of the harpy.Call
// interface for the TestService.ServerStream() method.
type harpy_TestService_ServerStream_Call struct {
	ctx     context.Context
	service TestService
	in      chan *Request
	out     chan *Response
	err     error
}

// newHarpy_TestService_ServerStream_Call returns a new harpy.Call for the TestService.ServerStream() method.
func newHarpy_TestService_ServerStream_Call(ctx context.Context, service TestService) harpy.Call {
	c := &harpy_TestService_ServerStream_Call{ctx, service, make(chan *Request, 1), make(chan *Response, 1), nil}
	go c.run()
	return c
}

func (c *harpy_TestService_ServerStream_Call) Recv() (proto.Message, bool, error) {
	select {
	case <-c.ctx.Done():
		return nil, false, c.ctx.Err()
	case res, ok := <-c.out:
		if ok {
			return res, true, nil
		}
		return nil, false, c.err
	}
}

func (c *harpy_TestService_ServerStream_Call) Send(unmarshal harpy.RawMessage) error {
	req := &Request{}
	if err := unmarshal(req); err != nil {
		return err
	}

	select {
	case <-c.ctx.Done():
		return c.ctx.Err()
	case c.in <- req:
		return nil
	}
}

func (c *harpy_TestService_ServerStream_Call) Done() {
	close(c.in)
}

func (c *harpy_TestService_ServerStream_Call) run() {
	defer close(c.out)

	select {
	case <-c.ctx.Done():
		c.err = c.ctx.Err()
	case req, ok := <-c.in:
		if ok {
			c.err = c.service.ServerStream(c.ctx, req, c.out)
		} else {
			c.err = errors.New("Done() was called without sending a request")
		}
	}
}

// harpy_TestService_ClientStream_Method is an implementation of the harpy.Method
// interface for the TestService.ClientStream() method.
type harpy_TestService_ClientStream_Method struct {
	service TestService
}

func (m *harpy_TestService_ClientStream_Method) Name() string {
	return "ClientStream"
}

func (m *harpy_TestService_ClientStream_Method) ClientStreaming() bool {
	return true
}

func (m *harpy_TestService_ClientStream_Method) ServerStreaming() bool {
	return false
}

func (m *harpy_TestService_ClientStream_Method) NewCall(ctx context.Context) harpy.Call {
	return newHarpy_TestService_ClientStream_Call(ctx, m.service)
}

// harpy_TestService_ClientStream_Call is an implementation of the harpy.Call
// interface for the TestService.ClientStream() method.
type harpy_TestService_ClientStream_Call struct {
	ctx     context.Context
	service TestService
	in      chan *Request
	out     chan *Response
	err     error
}

// newHarpy_TestService_ClientStream_Call returns a new harpy.Call for the TestService.ClientStream() method.
func newHarpy_TestService_ClientStream_Call(ctx context.Context, service TestService) harpy.Call {
	c := &harpy_TestService_ClientStream_Call{ctx, service, make(chan *Request, 1), make(chan *Response, 1), nil}
	go c.run()
	return c
}

func (c *harpy_TestService_ClientStream_Call) Recv() (proto.Message, bool, error) {
	select {
	case <-c.ctx.Done():
		return nil, false, c.ctx.Err()
	case res, ok := <-c.out:
		if ok {
			return res, true, nil
		}
		return nil, false, c.err
	}
}

func (c *harpy_TestService_ClientStream_Call) Send(unmarshal harpy.RawMessage) error {
	req := &Request{}
	if err := unmarshal(req); err != nil {
		return err
	}

	select {
	case <-c.ctx.Done():
		return c.ctx.Err()
	case c.in <- req:
		return nil
	}
}

func (c *harpy_TestService_ClientStream_Call) Done() {
	close(c.in)
}

func (c *harpy_TestService_ClientStream_Call) run() {
	defer close(c.out)

	res, err := c.service.ClientStream(c.ctx, c.in)
	if err != nil {
		c.err = err
	} else {
		c.out <- res // buffered, never blocks
	}
}

// harpy_TestService_BidirectionalStream_Method is an implementation of the harpy.Method
// interface for the TestService.BidirectionalStream() method.
type harpy_TestService_BidirectionalStream_Method struct {
	service TestService
}

func (m *harpy_TestService_BidirectionalStream_Method) Name() string {
	return "BidirectionalStream"
}

func (m *harpy_TestService_BidirectionalStream_Method) ClientStreaming() bool {
	return true
}

func (m *harpy_TestService_BidirectionalStream_Method) ServerStreaming() bool {
	return true
}

func (m *harpy_TestService_BidirectionalStream_Method) NewCall(ctx context.Context) harpy.Call {
	return newHarpy_TestService_BidirectionalStream_Call(ctx, m.service)
}

// harpy_TestService_BidirectionalStream_Call is an implementation of the harpy.Call
// interface for the TestService.BidirectionalStream() method.
type harpy_TestService_BidirectionalStream_Call struct {
	ctx     context.Context
	service TestService
	in      chan *Request
	out     chan *Response
	err     error
}

// newHarpy_TestService_BidirectionalStream_Call returns a new harpy.Call for the TestService.BidirectionalStream() method.
func newHarpy_TestService_BidirectionalStream_Call(ctx context.Context, service TestService) harpy.Call {
	c := &harpy_TestService_BidirectionalStream_Call{ctx, service, make(chan *Request, 1), make(chan *Response, 1), nil}
	go c.run()
	return c
}

func (c *harpy_TestService_BidirectionalStream_Call) Recv() (proto.Message, bool, error) {
	select {
	case <-c.ctx.Done():
		return nil, false, c.ctx.Err()
	case res, ok := <-c.out:
		if ok {
			return res, true, nil
		}
		return nil, false, c.err
	}
}

func (c *harpy_TestService_BidirectionalStream_Call) Send(unmarshal harpy.RawMessage) error {
	req := &Request{}
	if err := unmarshal(req); err != nil {
		return err
	}

	select {
	case <-c.ctx.Done():
		return c.ctx.Err()
	case c.in <- req:
		return nil
	}
}

func (c *harpy_TestService_BidirectionalStream_Call) Done() {
	close(c.in)
}

func (c *harpy_TestService_BidirectionalStream_Call) run() {
	defer close(c.out)
	c.err = c.service.BidirectionalStream(c.ctx, c.in, c.out)
}
