// Code generated by protoc-gen-go-harpy. DO NOT EDIT.
// versions:
// 	protoc-gen-go v0.0.0+de8f4a0
// 	protoc        v3.17.3
// source: github.com/dogmatiq/harpy/example/api.proto

package example

import "context"

// HarpyExampleAPIServer is an interface for types that implement the ExampleAPI service.
type HarpyExampleAPIServer interface {
	Unary(context.Context, Request) (Response, error)
	ServerStream(context.Context, Request, chan<- Response) error
	ClientStream(context.Context, <-chan Request) (Response, error)
	BidirectionalStream(context.Context, <-chan Request, chan<- Response) error
}
