// Code generated by protoc-gen-go-harpy. DO NOT EDIT.
// versions:
// 	protoc-gen-go v0.0.0+42ea9ee
// 	protoc        v3.17.3
// source: github.com/dogmatiq/harpy/example/api.proto

package example

import "context"

// ExampleAPI is an interface the harpy.example.ExampleAPI service.
type ExampleAPI interface {
	Unary(context.Context, Request) (Response, error)
	ServerStream(context.Context, Request, chan<- Response) error
	ClientStream(context.Context, <-chan Request) (Response, error)
	BidirectionalStream(context.Context, <-chan Request, chan<- Response) error
}
