// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: github.com/dogmatiq/protean/internal/stringservice/service.proto

package stringservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToUpperRequest is the RPC input message for the StringService.ToUpper() RPC
// method.
type ToUpperRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OriginalString string                 `protobuf:"bytes,1,opt,name=original_string,json=originalString,proto3" json:"original_string,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToUpperRequest) Reset() {
	*x = ToUpperRequest{}
	mi := &file_github_com_dogmatiq_protean_internal_stringservice_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToUpperRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUpperRequest) ProtoMessage() {}

func (x *ToUpperRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_protean_internal_stringservice_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUpperRequest.ProtoReflect.Descriptor instead.
func (*ToUpperRequest) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescGZIP(), []int{0}
}

func (x *ToUpperRequest) GetOriginalString() string {
	if x != nil {
		return x.OriginalString
	}
	return ""
}

// ToUpperResponse is the RPC output message for the StringService.ToUpper() RPC
// method.
type ToUpperResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UppercaseString string                 `protobuf:"bytes,1,opt,name=uppercase_string,json=uppercaseString,proto3" json:"uppercase_string,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ToUpperResponse) Reset() {
	*x = ToUpperResponse{}
	mi := &file_github_com_dogmatiq_protean_internal_stringservice_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToUpperResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToUpperResponse) ProtoMessage() {}

func (x *ToUpperResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_protean_internal_stringservice_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToUpperResponse.ProtoReflect.Descriptor instead.
func (*ToUpperResponse) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescGZIP(), []int{1}
}

func (x *ToUpperResponse) GetUppercaseString() string {
	if x != nil {
		return x.UppercaseString
	}
	return ""
}

var File_github_com_dogmatiq_protean_internal_stringservice_service_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDesc = "" +
	"\n" +
	"@github.com/dogmatiq/protean/internal/stringservice/service.proto\x12\x0eprotean.string\"9\n" +
	"\x0eToUpperRequest\x12'\n" +
	"\x0foriginal_string\x18\x01 \x01(\tR\x0eoriginalString\"<\n" +
	"\x0fToUpperResponse\x12)\n" +
	"\x10uppercase_string\x18\x01 \x01(\tR\x0fuppercaseString2[\n" +
	"\rStringService\x12J\n" +
	"\aToUpper\x12\x1e.protean.string.ToUpperRequest\x1a\x1f.protean.string.ToUpperResponseB4Z2github.com/dogmatiq/protean/internal/stringserviceb\x06proto3"

var (
	file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescData []byte
)

func file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDesc), len(file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDescData
}

var file_github_com_dogmatiq_protean_internal_stringservice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_protean_internal_stringservice_service_proto_goTypes = []any{
	(*ToUpperRequest)(nil),  // 0: protean.string.ToUpperRequest
	(*ToUpperResponse)(nil), // 1: protean.string.ToUpperResponse
}
var file_github_com_dogmatiq_protean_internal_stringservice_service_proto_depIdxs = []int32{
	0, // 0: protean.string.StringService.ToUpper:input_type -> protean.string.ToUpperRequest
	1, // 1: protean.string.StringService.ToUpper:output_type -> protean.string.ToUpperResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_protean_internal_stringservice_service_proto_init() }
func file_github_com_dogmatiq_protean_internal_stringservice_service_proto_init() {
	if File_github_com_dogmatiq_protean_internal_stringservice_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDesc), len(file_github_com_dogmatiq_protean_internal_stringservice_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_dogmatiq_protean_internal_stringservice_service_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_protean_internal_stringservice_service_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_protean_internal_stringservice_service_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_protean_internal_stringservice_service_proto = out.File
	file_github_com_dogmatiq_protean_internal_stringservice_service_proto_goTypes = nil
	file_github_com_dogmatiq_protean_internal_stringservice_service_proto_depIdxs = nil
}
