// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: github.com/dogmatiq/protean/internal/proteanpb/error.proto

package proteanpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Error is the message used to transfer information about an RPC error to a
// client.
//
// When serialized using the protojson package it conforms to the structure of a
// JSON-RPC v2 error object. See https://www.jsonrpc.org/specification#error_object.
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// SupportedMediaTypes is a list of media types supported by the server, in
// order of preference.
type SupportedMediaTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaTypes    []string               `protobuf:"bytes,1,rep,name=media_types,json=mediaTypes,proto3" json:"media_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedMediaTypes) Reset() {
	*x = SupportedMediaTypes{}
	mi := &file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedMediaTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedMediaTypes) ProtoMessage() {}

func (x *SupportedMediaTypes) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedMediaTypes.ProtoReflect.Descriptor instead.
func (*SupportedMediaTypes) Descriptor() ([]byte, []int) {
	return file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescGZIP(), []int{1}
}

func (x *SupportedMediaTypes) GetMediaTypes() []string {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

var File_github_com_dogmatiq_protean_internal_proteanpb_error_proto protoreflect.FileDescriptor

const file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDesc = "" +
	"\n" +
	":github.com/dogmatiq/protean/internal/proteanpb/error.proto\x12\n" +
	"protean.v1\x1a\x19google/protobuf/any.proto\"_\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"6\n" +
	"\x13SupportedMediaTypes\x12\x1f\n" +
	"\vmedia_types\x18\x01 \x03(\tR\n" +
	"mediaTypesB0Z.github.com/dogmatiq/protean/internal/proteanpbb\x06proto3"

var (
	file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescOnce sync.Once
	file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescData []byte
)

func file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescGZIP() []byte {
	file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescOnce.Do(func() {
		file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDesc), len(file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDesc)))
	})
	return file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDescData
}

var file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_goTypes = []any{
	(*Error)(nil),               // 0: protean.v1.Error
	(*SupportedMediaTypes)(nil), // 1: protean.v1.SupportedMediaTypes
	(*anypb.Any)(nil),           // 2: google.protobuf.Any
}
var file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_depIdxs = []int32{
	2, // 0: protean.v1.Error.data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_init() }
func file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_init() {
	if File_github_com_dogmatiq_protean_internal_proteanpb_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDesc), len(file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_goTypes,
		DependencyIndexes: file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_depIdxs,
		MessageInfos:      file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_msgTypes,
	}.Build()
	File_github_com_dogmatiq_protean_internal_proteanpb_error_proto = out.File
	file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_goTypes = nil
	file_github_com_dogmatiq_protean_internal_proteanpb_error_proto_depIdxs = nil
}
